import { nanoid } from "@reduxjs/toolkit";

const avatarSrc = '/assets/images/avatars';
const levelSrc = '/assets/images/avatar-frame-circle';
type IItemType = {src: string, title: string}
export enum FrameTheams {
    dark = '#202020',
    light = '#ffffff',
}

export enum LevelTypes {
    level1 = 'Uncommon',
    level2 = 'Common',
    level3 = 'Rare',
    level4 = 'Rare Gold one star',
    level5 = 'Rare Gold two star',
    level6 = 'Rare Gold three star',
    level7 = 'Supper Rare',
    level8 = 'Supper Rare 2'
}
export type IRerityLevel = {[rerityLevelName: string]: IItemType}
export type IAvatars = {[categoryName: string]:  {src: string, _id: string, title: string, rerityLeve: IRerityLevel[number], frameTheam?:FrameTheams}[]}
export const AvatarRerityLevels:IRerityLevel = {
    level1: {title: LevelTypes.level1, src: `${levelSrc}/frame-sky.png`},
    level2: {title: LevelTypes.level2, src: `${levelSrc}/frame-gold.png`},
    level3: {title: LevelTypes.level3, src: `${levelSrc}/frame-pink.png`},
    level4: {title: LevelTypes.level4, src: `${levelSrc}/frame-level-1.png`},
    level5: {title: LevelTypes.level5, src: `${levelSrc}/frame-level-2.png`},
    level6: {title: LevelTypes.level6, src: `${levelSrc}/frame-level-3.png`},
    level7: {title: LevelTypes.level7, src: `${levelSrc}/frame-demon.png`},
    level8: {title: LevelTypes.level8, src: `${levelSrc}/frame-rabbit.png`},
}
export const AvatarGroups: IAvatars = {
    'abc-warriors-characters': [
        {_id: nanoid(), title: 'Black Blood', src: `${avatarSrc}/abc-warriors-characters/black-blood.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Hammerstein', src: `${avatarSrc}/abc-warriors-characters/hammerstein.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Joe Pineapples', src: `${avatarSrc}/abc-warriors-characters/joe-pineapples.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Mek-Quake', src: `${avatarSrc}/abc-warriors-characters/mek-quake.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Mongrol', src: `${avatarSrc}/abc-warriors-characters/mongrol.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'adventure-time-cartoon': [
        {_id: nanoid(), title: 'Bmo', src: `${avatarSrc}/adventure-time-cartoon/bmo.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Finn', src: `${avatarSrc}/adventure-time-cartoon/finn.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Gunter', src: `${avatarSrc}/adventure-time-cartoon/gunter.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Ice King', src: `${avatarSrc}/adventure-time-cartoon/ice-king.png`, rerityLeve: AvatarRerityLevels.level3},
        {_id: nanoid(), title: 'Jake', src: `${avatarSrc}/adventure-time-cartoon/jake.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Lumpy Space Princess', src: `${avatarSrc}/adventure-time-cartoon/lumpy-space-princess.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Marceline', src: `${avatarSrc}/adventure-time-cartoon/marceline.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Princess Bubblegum', src: `${avatarSrc}/adventure-time-cartoon/princess-bubblegum.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'animation-characters': [
        {_id: nanoid(), title: 'Amethyst Universe', src: `${avatarSrc}/animation-characters/amethyst-universe.png`, rerityLeve: AvatarRerityLevels.level3},
        {_id: nanoid(), title: 'Badtz Maru', src: `${avatarSrc}/animation-characters/badtz-maru.png`, rerityLeve: AvatarRerityLevels.level3},
        {_id: nanoid(), title: 'Bill Cipher', src: `${avatarSrc}/animation-characters/bill-cipher.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Brave', src: `${avatarSrc}/animation-characters/brave.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Brutus', src: `${avatarSrc}/animation-characters/brutus.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Cheburashka', src: `${avatarSrc}/animation-characters/cheburashka.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Fairy', src: `${avatarSrc}/animation-characters/fairy.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Genie', src: `${avatarSrc}/animation-characters/genie.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Grim Adventures Of Billy And Mandy', src: `${avatarSrc}/animation-characters/grim-adventures-of-billy-and-mandy.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Grinch', src: `${avatarSrc}/animation-characters/grinch.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Hello Kitty', src: `${avatarSrc}/animation-characters/hello-kitty.png`, rerityLeve: AvatarRerityLevels.level1, frameTheam: FrameTheams.light},
        {_id: nanoid(), title: 'Jerry', src: `${avatarSrc}/animation-characters/jerry.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Jimmy Neutron', src: `${avatarSrc}/animation-characters/jimmy-neutron.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Keiji Akaashi', src: `${avatarSrc}/animation-characters/keiji-akaashi.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Kermit The Frog', src: `${avatarSrc}/animation-characters/kermit-the-frog.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Keroppi', src: `${avatarSrc}/animation-characters/keroppi.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Kiki', src: `${avatarSrc}/animation-characters/kiki.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Kuroo', src: `${avatarSrc}/animation-characters/kuroo.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Lala', src: `${avatarSrc}/animation-characters/lala.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Madagascar', src: `${avatarSrc}/animation-characters/madagascar.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Mermaid', src: `${avatarSrc}/animation-characters/mermaid.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Morty Smith', src: `${avatarSrc}/animation-characters/morty-smith.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'My Melody', src: `${avatarSrc}/animation-characters/my-melody.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Ninja Turtle', src: `${avatarSrc}/animation-characters/ninja-turtle.png`, rerityLeve: AvatarRerityLevels.level4},
        {_id: nanoid(), title: 'Oggy', src: `${avatarSrc}/animation-characters/oggy.png`, rerityLeve: AvatarRerityLevels.level3},
        {_id: nanoid(), title: 'Olive Oyl', src: `${avatarSrc}/animation-characters/olive-oyl.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Peter Pan', src: `${avatarSrc}/animation-characters/peter-pan.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Pochacco', src: `${avatarSrc}/animation-characters/pochacco.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Popeye', src: `${avatarSrc}/animation-characters/popeye.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Rick Sanchez', src: `${avatarSrc}/animation-characters/rick-sanchez.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Sailor Moon', src: `${avatarSrc}/animation-characters/sailor-moon.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Saitama', src: `${avatarSrc}/animation-characters/saitama.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Scooby Doo', src: `${avatarSrc}/animation-characters/scooby-doo.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Scooby Doo Daphne Blake', src: `${avatarSrc}/animation-characters/scooby-doo-daphne-blake.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Scooby Doo Fred Jones', src: `${avatarSrc}/animation-characters/scooby-doo-fred-jones.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Scooby Doo Shaggy Rogers', src: `${avatarSrc}/animation-characters/scooby-doo-shaggy-rogers.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Scooby Doo Velma Dinkley', src: `${avatarSrc}/animation-characters/scooby-doo-velma-dinkley.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Shoyo Hinata', src: `${avatarSrc}/animation-characters/shoyo-hinata.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Shrek', src: `${avatarSrc}/animation-characters/shrek.png`, rerityLeve: AvatarRerityLevels.level4},
        {_id: nanoid(), title: 'Smurf', src: `${avatarSrc}/animation-characters/smurf.png`, rerityLeve: AvatarRerityLevels.level5},
        {_id: nanoid(), title: 'Son Goku', src: `${avatarSrc}/animation-characters/son-goku.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Spongebob Squarepants', src: `${avatarSrc}/animation-characters/spongebob-squarepants.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Stitch Character', src: `${avatarSrc}/animation-characters/stitch-character.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Tanjiro Kamado', src: `${avatarSrc}/animation-characters/tanjiro-kamado.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Tobio Kageyama', src: `${avatarSrc}/animation-characters/tobio-kageyama.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Tom', src: `${avatarSrc}/animation-characters/tom.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Totoro', src: `${avatarSrc}/animation-characters/totoro.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Woody Woodpecker', src: `${avatarSrc}/animation-characters/woody-woodpecker.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'dc-characters': [
        {_id: nanoid(), title: 'Aquaman', src: `${avatarSrc}/dc-characters/aquaman.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Atom', src: `${avatarSrc}/dc-characters/atom.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Batman', src: `${avatarSrc}/dc-characters/batman.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Catwoman', src: `${avatarSrc}/dc-characters/catwoman.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Cyborg', src: `${avatarSrc}/dc-characters/cyborg.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Green Arrow DC', src: `${avatarSrc}/dc-characters/green-arrow-dc.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Green Lantern DC', src: `${avatarSrc}/dc-characters/green-lantern-dc.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Harley Quinn DC', src: `${avatarSrc}/dc-characters/harley-quinn-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Harley Quinn Suicide Squad', src: `${avatarSrc}/dc-characters/harley-quinn-suicide-squad.png`, rerityLeve: AvatarRerityLevels.level7},
        {_id: nanoid(), title: 'Hawkgirl', src: `${avatarSrc}/dc-characters/hawkgirl.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Hawkman', src: `${avatarSrc}/dc-characters/hawkman.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Isis', src: `${avatarSrc}/dc-characters/isis.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Joker DC', src: `${avatarSrc}/dc-characters/joker-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Joker Suicide Squad', src: `${avatarSrc}/dc-characters/joker-suicide-squad.png`, rerityLeve: AvatarRerityLevels.level7},
        {_id: nanoid(), title: 'Knight Helmet', src: `${avatarSrc}/dc-characters/knight-helmet.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Lex Luthor', src: `${avatarSrc}/dc-characters/lex-luthor.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Nightwing', src: `${avatarSrc}/dc-characters/nightwing.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Superman DC', src: `${avatarSrc}/dc-characters/superman-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'The Flash Head', src: `${avatarSrc}/dc-characters/the-flash-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Zatanna', src: `${avatarSrc}/dc-characters/zatanna.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'futurama': [
        {_id: nanoid(), title: 'Futurama Amy Wong', src: `${avatarSrc}/futurama/futurama-amy-wong.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Futurama Bender', src: `${avatarSrc}/futurama/futurama-bender.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Futurama Fry', src: `${avatarSrc}/futurama/futurama-fry.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Futurama Hermes Conrad', src: `${avatarSrc}/futurama/futurama-hermes-conrad.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Futurama Leela', src: `${avatarSrc}/futurama/futurama-leela.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Futurama Lrrr', src: `${avatarSrc}/futurama/futurama-lrrr.png`, rerityLeve: AvatarRerityLevels.level5},
        {_id: nanoid(), title: 'Futurama Mom', src: `${avatarSrc}/futurama/futurama-mom.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Futurama Nibbler', src: `${avatarSrc}/futurama/futurama-nibbler.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Futurama Professor Farnsworth', src: `${avatarSrc}/futurama/futurama-professor-farnsworth.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Futurama Zapp Brannigan', src: `${avatarSrc}/futurama/futurama-zapp-brannigan.png`, rerityLeve: AvatarRerityLevels.level2},
        {_id: nanoid(), title: 'Futurama Zoidberg', src: `${avatarSrc}/futurama/futurama-zoidberg.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'gaming': [
        {_id: nanoid(), title: 'Bendy', src: `${avatarSrc}/gaming/bendy.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Day Of The Tentacle', src: `${avatarSrc}/gaming/day-of-the-tentacle.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Eggman Robotnik', src: `${avatarSrc}/gaming/eggman-robotnik.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Five Nights At Freddys', src: `${avatarSrc}/gaming/five-nights-at-freddys.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Fortnite Llama', src: `${avatarSrc}/gaming/fortnite-llama.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Fursona', src: `${avatarSrc}/gaming/fursona.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Genshin Impact Xiao', src: `${avatarSrc}/gaming/genshin-impact-xiao.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Hatsune Miku', src: `${avatarSrc}/gaming/hatsune-miku.png`, rerityLeve: AvatarRerityLevels.level8},
        {_id: nanoid(), title: 'Helpy', src: `${avatarSrc}/gaming/helpy.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Jetpack Joyride', src: `${avatarSrc}/gaming/jetpack-joyride.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Luigi', src: `${avatarSrc}/gaming/luigi.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Sonic the Hedgehog', src: `${avatarSrc}/gaming/sonic-the-hedgehog.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Spyro', src: `${avatarSrc}/gaming/spyro.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Super Mario', src: `${avatarSrc}/gaming/super-mario.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Tails Prower', src: `${avatarSrc}/gaming/tails-prower.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Theodore Peterson', src: `${avatarSrc}/gaming/theodore-peterson.png`, rerityLeve: AvatarRerityLevels.level1},
        {_id: nanoid(), title: 'Undyne', src: `${avatarSrc}/gaming/undyne.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'marvel characters': [
        {_id: nanoid(), title: 'Beast', src: `${avatarSrc}/marvel-characters/beast.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Black Widow', src: `${avatarSrc}/marvel-characters/black-widow.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Captain America', src: `${avatarSrc}/marvel-characters/captain-america.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Cyclops Marvel', src: `${avatarSrc}/marvel-characters/cyclops-marvel.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Deadpool', src: `${avatarSrc}/marvel-characters/deadpool.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Gambit', src: `${avatarSrc}/marvel-characters/gambit.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Groot', src: `${avatarSrc}/marvel-characters/groot.png`, rerityLeve: AvatarRerityLevels.level8},
        {_id: nanoid(), title: 'Hawkeye', src: `${avatarSrc}/marvel-characters/hawkeye.png`, rerityLeve: AvatarRerityLevels.level7},
        {_id: nanoid(), title: 'Hellcat', src: `${avatarSrc}/marvel-characters/hellcat.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Hulk', src: `${avatarSrc}/marvel-characters/hulk.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Human Torch', src: `${avatarSrc}/marvel-characters/human-torch.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Iron Man', src: `${avatarSrc}/marvel-characters/iron-man.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Jean Grey', src: `${avatarSrc}/marvel-characters/jean-grey.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Jessica Jones', src: `${avatarSrc}/marvel-characters/jessica-jones.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Logan X Men', src: `${avatarSrc}/marvel-characters/logan-x-men.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Luke Cage', src: `${avatarSrc}/marvel-characters/luke-cage.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Magneto', src: `${avatarSrc}/marvel-characters/magneto.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Mystique', src: `${avatarSrc}/marvel-characters/mystique.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Professor X', src: `${avatarSrc}/marvel-characters/professor-x.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Purple Man', src: `${avatarSrc}/marvel-characters/purple-man.png`, rerityLeve: AvatarRerityLevels.level7},
        {_id: nanoid(), title: 'Spider-Man Head', src: `${avatarSrc}/marvel-characters/spider-man-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Storm Marvel', src: `${avatarSrc}/marvel-characters/storm-marvel.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Thanos', src: `${avatarSrc}/marvel-characters/thanos.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Thor', src: `${avatarSrc}/marvel-characters/thor.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Venom Head', src: `${avatarSrc}/marvel-characters/venom-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: 'Wolverine', src: `${avatarSrc}/marvel-characters/wolverine.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'movie characters': [
        {_id: nanoid(), title: "Albus Dumbledore", src: `${avatarSrc}/movie-characters/albus-dumbledore.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Anonymous Mask", src: `${avatarSrc}/movie-characters/anonymous-mask.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Bella Swan", src: `${avatarSrc}/movie-characters/bella-swan.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Borg Head", src: `${avatarSrc}/movie-characters/borg-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Chucky", src: `${avatarSrc}/movie-characters/chucky.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Cookie Monster", src: `${avatarSrc}/movie-characters/cookie-monster.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Cylon Head", src: `${avatarSrc}/movie-characters/cylon-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Cylon Head New", src: `${avatarSrc}/movie-characters/cylon-head-new.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Dobby", src: `${avatarSrc}/movie-characters/dobby.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Draco Malfoy", src: `${avatarSrc}/movie-characters/draco-malfoy.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Edward Cullen", src: `${avatarSrc}/movie-characters/edward-cullen.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Freddy Krueger", src: `${avatarSrc}/movie-characters/freddy-krueger.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Fsociety Mask", src: `${avatarSrc}/movie-characters/fsociety-mask.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Gizmo", src: `${avatarSrc}/movie-characters/gizmo.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Grey", src: `${avatarSrc}/movie-characters/grey.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Harry Potter", src: `${avatarSrc}/movie-characters/harry-potter.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Hedwig", src: `${avatarSrc}/movie-characters/hedwig.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Hellraiser Pinhead", src: `${avatarSrc}/movie-characters/hellraiser-pinhead.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Hermione", src: `${avatarSrc}/movie-characters/hermione.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Jason Voorhees", src: `${avatarSrc}/movie-characters/jason-voorhees.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "John Wick", src: `${avatarSrc}/movie-characters/john-wick.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Lord Voldemort", src: `${avatarSrc}/movie-characters/lord-voldemort.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Martian", src: `${avatarSrc}/movie-characters/martian.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Michael Myers", src: `${avatarSrc}/movie-characters/michael-myers.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Michonne", src: `${avatarSrc}/movie-characters/michonne.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Minerva Mcgonagall", src: `${avatarSrc}/movie-characters/minerva-mcgonagall.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Mummy", src: `${avatarSrc}/movie-characters/mummy.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Na'vi Avatar", src: `${avatarSrc}/movie-characters/na'vi-avatar.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Pennywise", src: `${avatarSrc}/movie-characters/pennywise.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Predator", src: `${avatarSrc}/movie-characters/predator.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Ron Weasley", src: `${avatarSrc}/movie-characters/ron-weasley.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Saul Goodman", src: `${avatarSrc}/movie-characters/saul-goodman.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Scream", src: `${avatarSrc}/movie-characters/scream.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Victoria Secret Angel", src: `${avatarSrc}/movie-characters/victoria-secret-angel.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Walter White", src: `${avatarSrc}/movie-characters/walter-white.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'star-wars-movie': [
        {_id: nanoid(), title: "Baby Yoda", src: `${avatarSrc}/star-wars-movie/baby-yoda.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "C-3PO", src: `${avatarSrc}/star-wars-movie/c-3po.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Chewbacca", src: `${avatarSrc}/star-wars-movie/chewbacca.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Darth Vader", src: `${avatarSrc}/star-wars-movie/darth-vader.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Lightsaber", src: `${avatarSrc}/star-wars-movie/lightsaber.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Luke Skywalker", src: `${avatarSrc}/star-wars-movie/luke-skywalker.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Mando", src: `${avatarSrc}/star-wars-movie/mando.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Stormtrooper", src: `${avatarSrc}/star-wars-movie/stormtrooper.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'bt21': [
        {_id: nanoid(), title: "BT21 Chimmy", src:`${avatarSrc}/bt21/bt21-chimmy.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Cooky", src:`${avatarSrc}/bt21/bt21-cooky.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Koya", src:`${avatarSrc}/bt21/bt21-koya.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Mang", src:`${avatarSrc}/bt21/bt21-mang.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Rj",   src:`${avatarSrc}/bt21/bt21-rj.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Shooky", src:`${avatarSrc}/bt21/bt21-shooky.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "BT21 Tata", src:`${avatarSrc}/bt21/bt21-tata.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'the-simpsons-movie': [
        {_id: nanoid(), title: "Homer Simpson", src: `${avatarSrc}/the-simpsons-movie/homer-simpson.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'steven-universe': [
        {_id: nanoid(), title: "Connie", src: `${avatarSrc}/steven-universe/connie.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Garnet Universe", src: `${avatarSrc}/steven-universe/garnet-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Greg Universe", src: `${avatarSrc}/steven-universe/greg-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Jasper Universe", src: `${avatarSrc}/steven-universe/jasper-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Lapis Lazuli Universe", src: `${avatarSrc}/steven-universe/lapis-lazuli-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Pearl Universe", src: `${avatarSrc}/steven-universe/pearl-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Peridot Universe", src: `${avatarSrc}/steven-universe/peridot-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Rose Quartz Universe", src: `${avatarSrc}/steven-universe/rose-quartz-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Ruby Universe", src: `${avatarSrc}/steven-universe/ruby-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Sapphire Universe", src: `${avatarSrc}/steven-universe/sapphire-universe.png`, rerityLeve: AvatarRerityLevels.level6},
        {_id: nanoid(), title: "Steven Universe", src: `${avatarSrc}/steven-universe/steven-universe.png`, rerityLeve: AvatarRerityLevels.level6}
    ],    
};
    
    