const baseUrl = '/assets/images/avatars';
export type IAvatars = {[categoryName: string]: {src: string, title: string}[]};
export const Avatars: IAvatars = {
    'abc-warriors-characters': [
        {title: 'Black Blood', src: `${baseUrl}/abc-warriors-characters/black-blood.png`},
        {title: 'Hammerstein', src: `${baseUrl}/abc-warriors-characters/hammerstein.png`},
        {title: 'Joe Pineapples', src: `${baseUrl}/abc-warriors-characters/joe-pineapples.png`},
        {title: 'Mek-Quake', src: `${baseUrl}/abc-warriors-characters/mek-quake.png`},
        {title: 'Mongrol', src: `${baseUrl}/abc-warriors-characters/mongrol.png`},
    ],
    'adventure-time-cartoon': [
        {title: 'Bmo', src: `${baseUrl}/adventure-time-cartoon/bmo.png`},
        {title: 'Finn', src: `${baseUrl}/adventure-time-cartoon/finn.png`},
        {title: 'Gunter', src: `${baseUrl}/adventure-time-cartoon/gunter.png`},
        {title: 'Ice King', src: `${baseUrl}/adventure-time-cartoon/ice-king.png`},
        {title: 'Jake', src: `${baseUrl}/adventure-time-cartoon/jake.png`},
        {title: 'Lumpy Space Princess', src: `${baseUrl}/adventure-time-cartoon/lumpy-space-princess.png`},
        {title: 'Marceline', src: `${baseUrl}/adventure-time-cartoon/marceline.png`},
        {title: 'Princess Bubblegum', src: `${baseUrl}/adventure-time-cartoon/princess-bubblegum.png`},
    ],
    
    'animation-characters': [
        {title: 'Amethyst Universe', src: `${baseUrl}/animation-characters/amethyst-universe.png`},
        {title: 'Badtz Maru', src: `${baseUrl}/animation-characters/badtz-maru.png`},
        {title: 'Bill Cipher', src: `${baseUrl}/animation-characters/bill-cipher.png`},
        {title: 'Brave', src: `${baseUrl}/animation-characters/brave.png`},
        {title: 'Brutus', src: `${baseUrl}/animation-characters/brutus.png`},
        {title: 'Cheburashka', src: `${baseUrl}/animation-characters/cheburashka.png`},
        {title: 'Fairy', src: `${baseUrl}/animation-characters/fairy.png`},
        {title: 'Genie', src: `${baseUrl}/animation-characters/genie.png`},
        {title: 'Grim Adventures Of Billy And Mandy', src: `${baseUrl}/animation-characters/grim-adventures-of-billy-and-mandy.png`},
        {title: 'Grinch', src: `${baseUrl}/animation-characters/grinch.png`},
        {title: 'Hello Kitty', src: `${baseUrl}/animation-characters/hello-kitty.png`},
        {title: 'Jerry', src: `${baseUrl}/animation-characters/jerry.png`},
        {title: 'Jimmy Neutron', src: `${baseUrl}/animation-characters/jimmy-neutron.png`},
        {title: 'Keiji Akaashi', src: `${baseUrl}/animation-characters/keiji-akaashi.png`},
        {title: 'Kermit The Frog', src: `${baseUrl}/animation-characters/kermit-the-frog.png`},
        {title: 'Keroppi', src: `${baseUrl}/animation-characters/keroppi.png`},
        {title: 'Kiki', src: `${baseUrl}/animation-characters/kiki.png`},
        {title: 'Kuroo', src: `${baseUrl}/animation-characters/kuroo.png`},
        {title: 'Lala', src: `${baseUrl}/animation-characters/lala.png`},
        {title: 'Madagascar', src: `${baseUrl}/animation-characters/madagascar.png`},
        {title: 'Mermaid', src: `${baseUrl}/animation-characters/mermaid.png`},
        {title: 'Morty Smith', src: `${baseUrl}/animation-characters/morty-smith.png`},
        {title: 'My Melody', src: `${baseUrl}/animation-characters/my-melody.png`},
        {title: 'Ninja Turtle', src: `${baseUrl}/animation-characters/ninja-turtle.png`},
        {title: 'Oggy', src: `${baseUrl}/animation-characters/oggy.png`},
        {title: 'Olive Oyl', src: `${baseUrl}/animation-characters/olive-oyl.png`},
        {title: 'Peter Pan', src: `${baseUrl}/animation-characters/peter-pan.png`},
        {title: 'Pochacco', src: `${baseUrl}/animation-characters/pochacco.png`},
        {title: 'Popeye', src: `${baseUrl}/animation-characters/popeye.png`},
        {title: 'Rick Sanchez', src: `${baseUrl}/animation-characters/rick-sanchez.png`},
        {title: 'Sailor Moon', src: `${baseUrl}/animation-characters/sailor-moon.png`},
        {title: 'Saitama', src: `${baseUrl}/animation-characters/saitama.png`},
        {title: 'Scooby Doo', src: `${baseUrl}/animation-characters/scooby-doo.png`},
        {title: 'Scooby Doo Daphne Blake', src: `${baseUrl}/animation-characters/scooby-doo-daphne-blake.png`},
        {title: 'Scooby Doo Fred Jones', src: `${baseUrl}/animation-characters/scooby-doo-fred-jones.png`},
        {title: 'Scooby Doo Shaggy Rogers', src: `${baseUrl}/animation-characters/scooby-doo-shaggy-rogers.png`},
        {title: 'Scooby Doo Velma Dinkley', src: `${baseUrl}/animation-characters/scooby-doo-velma-dinkley.png`},
        {title: 'Shoyo Hinata', src: `${baseUrl}/animation-characters/shoyo-hinata.png`},
        {title: 'Shrek', src: `${baseUrl}/animation-characters/shrek.png`},
        {title: 'Smurf', src: `${baseUrl}/animation-characters/smurf.png`},
        {title: 'Son Goku', src: `${baseUrl}/animation-characters/son-goku.png`},
        {title: 'Spongebob Squarepants', src: `${baseUrl}/animation-characters/spongebob-squarepants.png`},
        {title: 'Stitch Character', src: `${baseUrl}/animation-characters/stitch-character.png`},
        {title: 'Tanjiro Kamado', src: `${baseUrl}/animation-characters/tanjiro-kamado.png`},
        {title: 'Tobio Kageyama', src: `${baseUrl}/animation-characters/tobio-kageyama.png`},
        {title: 'Tom', src: `${baseUrl}/animation-characters/tom.png`},
        {title: 'Totoro', src: `${baseUrl}/animation-characters/totoro.png`},
        {title: 'Woody Woodpecker', src: `${baseUrl}/animation-characters/woody-woodpecker.png`},
    ],
    
};