const avatarSrc = '/assets/images/avatars';
const levelSrc = '/assets/images/avatar-frame-circle';
type IItemType = {src: string, title: string}
export enum FrameTheams {
    dark = '#202020',
    light = '#ffffff',
}

export enum LevelTypes {
    level1 = 'Uncommon',
    level2 = 'Common',
    level3 = 'Rare',
    level4 = 'Rare Gold one star',
    level5 = 'Rare Gold two star',
    level6 = 'Rare Gold three star',
    level7 = 'Supper Rare',
    level8 = 'Supper Rare 2'
}
export type IRerityLevel = {[rerityLevelName: string]: IItemType}
export type IAvatars = {[categoryName: string]:  {src: string, title: string, rerityLeve: IRerityLevel[number], frameTheam?:FrameTheams}[]}
export const AvatarRerityLevels:IRerityLevel = {
    level1: {title: LevelTypes.level1, src: `${levelSrc}/frame-sky.png`},
    level2: {title: LevelTypes.level2, src: `${levelSrc}/frame-gold.png`},
    level3: {title: LevelTypes.level3, src: `${levelSrc}/frame-pink.png`},
    level4: {title: LevelTypes.level4, src: `${levelSrc}/frame-level-1.png`},
    level5: {title: LevelTypes.level5, src: `${levelSrc}/frame-level-2.png`},
    level6: {title: LevelTypes.level6, src: `${levelSrc}/frame-level-3.png`},
    level7: {title: LevelTypes.level7, src: `${levelSrc}/frame-demon.png`},
    level8: {title: LevelTypes.level8, src: `${levelSrc}/frame-rabbit.png`},
}
export const AvatarGroups: IAvatars = {
    'abc warriors characters': [
        {title: 'Black Blood', src: `${avatarSrc}/abc-warriors-characters/black-blood.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Hammerstein', src: `${avatarSrc}/abc-warriors-characters/hammerstein.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Joe Pineapples', src: `${avatarSrc}/abc-warriors-characters/joe-pineapples.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Mek-Quake', src: `${avatarSrc}/abc-warriors-characters/mek-quake.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Mongrol', src: `${avatarSrc}/abc-warriors-characters/mongrol.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'adventure time cartoon': [
        {title: 'Bmo', src: `${avatarSrc}/adventure-time-cartoon/bmo.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Finn', src: `${avatarSrc}/adventure-time-cartoon/finn.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Gunter', src: `${avatarSrc}/adventure-time-cartoon/gunter.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Ice King', src: `${avatarSrc}/adventure-time-cartoon/ice-king.png`, rerityLeve: AvatarRerityLevels.level3},
        {title: 'Jake', src: `${avatarSrc}/adventure-time-cartoon/jake.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Lumpy Space Princess', src: `${avatarSrc}/adventure-time-cartoon/lumpy-space-princess.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Marceline', src: `${avatarSrc}/adventure-time-cartoon/marceline.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Princess Bubblegum', src: `${avatarSrc}/adventure-time-cartoon/princess-bubblegum.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'animation characters': [
        {title: 'Amethyst Universe', src: `${avatarSrc}/animation-characters/amethyst-universe.png`, rerityLeve: AvatarRerityLevels.level3},
        {title: 'Badtz Maru', src: `${avatarSrc}/animation-characters/badtz-maru.png`, rerityLeve: AvatarRerityLevels.level3},
        {title: 'Bill Cipher', src: `${avatarSrc}/animation-characters/bill-cipher.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Brave', src: `${avatarSrc}/animation-characters/brave.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Brutus', src: `${avatarSrc}/animation-characters/brutus.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Cheburashka', src: `${avatarSrc}/animation-characters/cheburashka.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Fairy', src: `${avatarSrc}/animation-characters/fairy.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Genie', src: `${avatarSrc}/animation-characters/genie.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Grim Adventures Of Billy And Mandy', src: `${avatarSrc}/animation-characters/grim-adventures-of-billy-and-mandy.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Grinch', src: `${avatarSrc}/animation-characters/grinch.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Hello Kitty', src: `${avatarSrc}/animation-characters/hello-kitty.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Jerry', src: `${avatarSrc}/animation-characters/jerry.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Jimmy Neutron', src: `${avatarSrc}/animation-characters/jimmy-neutron.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Keiji Akaashi', src: `${avatarSrc}/animation-characters/keiji-akaashi.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Kermit The Frog', src: `${avatarSrc}/animation-characters/kermit-the-frog.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Keroppi', src: `${avatarSrc}/animation-characters/keroppi.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Kiki', src: `${avatarSrc}/animation-characters/kiki.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Kuroo', src: `${avatarSrc}/animation-characters/kuroo.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Lala', src: `${avatarSrc}/animation-characters/lala.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Madagascar', src: `${avatarSrc}/animation-characters/madagascar.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Mermaid', src: `${avatarSrc}/animation-characters/mermaid.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Morty Smith', src: `${avatarSrc}/animation-characters/morty-smith.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'My Melody', src: `${avatarSrc}/animation-characters/my-melody.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Ninja Turtle', src: `${avatarSrc}/animation-characters/ninja-turtle.png`, rerityLeve: AvatarRerityLevels.level4},
        {title: 'Oggy', src: `${avatarSrc}/animation-characters/oggy.png`, rerityLeve: AvatarRerityLevels.level3},
        {title: 'Olive Oyl', src: `${avatarSrc}/animation-characters/olive-oyl.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Peter Pan', src: `${avatarSrc}/animation-characters/peter-pan.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Pochacco', src: `${avatarSrc}/animation-characters/pochacco.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Popeye', src: `${avatarSrc}/animation-characters/popeye.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Rick Sanchez', src: `${avatarSrc}/animation-characters/rick-sanchez.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Sailor Moon', src: `${avatarSrc}/animation-characters/sailor-moon.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Saitama', src: `${avatarSrc}/animation-characters/saitama.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Scooby Doo', src: `${avatarSrc}/animation-characters/scooby-doo.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Scooby Doo Daphne Blake', src: `${avatarSrc}/animation-characters/scooby-doo-daphne-blake.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Scooby Doo Fred Jones', src: `${avatarSrc}/animation-characters/scooby-doo-fred-jones.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Scooby Doo Shaggy Rogers', src: `${avatarSrc}/animation-characters/scooby-doo-shaggy-rogers.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Scooby Doo Velma Dinkley', src: `${avatarSrc}/animation-characters/scooby-doo-velma-dinkley.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Shoyo Hinata', src: `${avatarSrc}/animation-characters/shoyo-hinata.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Shrek', src: `${avatarSrc}/animation-characters/shrek.png`, rerityLeve: AvatarRerityLevels.level4},
        {title: 'Smurf', src: `${avatarSrc}/animation-characters/smurf.png`, rerityLeve: AvatarRerityLevels.level5},
        {title: 'Son Goku', src: `${avatarSrc}/animation-characters/son-goku.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Spongebob Squarepants', src: `${avatarSrc}/animation-characters/spongebob-squarepants.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Stitch Character', src: `${avatarSrc}/animation-characters/stitch-character.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Tanjiro Kamado', src: `${avatarSrc}/animation-characters/tanjiro-kamado.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Tobio Kageyama', src: `${avatarSrc}/animation-characters/tobio-kageyama.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Tom', src: `${avatarSrc}/animation-characters/tom.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Totoro', src: `${avatarSrc}/animation-characters/totoro.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Woody Woodpecker', src: `${avatarSrc}/animation-characters/woody-woodpecker.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'dc characters': [
        {title: 'Aquaman', src: `${avatarSrc}/dc-characters/aquaman.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Atom', src: `${avatarSrc}/dc-characters/atom.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Batman', src: `${avatarSrc}/dc-characters/batman.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Catwoman', src: `${avatarSrc}/dc-characters/catwoman.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Cyborg', src: `${avatarSrc}/dc-characters/cyborg.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Green Arrow DC', src: `${avatarSrc}/dc-characters/green-arrow-dc.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Green Lantern DC', src: `${avatarSrc}/dc-characters/green-lantern-dc.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Harley Quinn DC', src: `${avatarSrc}/dc-characters/harley-quinn-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Harley Quinn Suicide Squad', src: `${avatarSrc}/dc-characters/harley-quinn-suicide-squad.png`, rerityLeve: AvatarRerityLevels.level7},
        {title: 'Hawkgirl', src: `${avatarSrc}/dc-characters/hawkgirl.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Hawkman', src: `${avatarSrc}/dc-characters/hawkman.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Isis', src: `${avatarSrc}/dc-characters/isis.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Joker DC', src: `${avatarSrc}/dc-characters/joker-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Joker Suicide Squad', src: `${avatarSrc}/dc-characters/joker-suicide-squad.png`, rerityLeve: AvatarRerityLevels.level7},
        {title: 'Knight Helmet', src: `${avatarSrc}/dc-characters/knight-helmet.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Lex Luthor', src: `${avatarSrc}/dc-characters/lex-luthor.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Nightwing', src: `${avatarSrc}/dc-characters/nightwing.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Superman DC', src: `${avatarSrc}/dc-characters/superman-dc.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'The Flash Head', src: `${avatarSrc}/dc-characters/the-flash-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Zatanna', src: `${avatarSrc}/dc-characters/zatanna.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'futurama': [
        {title: 'Futurama Amy Wong', src: `${avatarSrc}/futurama/futurama-amy-wong.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Futurama Bender', src: `${avatarSrc}/futurama/futurama-bender.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Futurama Fry', src: `${avatarSrc}/futurama/futurama-fry.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Futurama Hermes Conrad', src: `${avatarSrc}/futurama/futurama-hermes-conrad.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Futurama Leela', src: `${avatarSrc}/futurama/futurama-leela.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Futurama Lrrr', src: `${avatarSrc}/futurama/futurama-lrrr.png`, rerityLeve: AvatarRerityLevels.level5},
        {title: 'Futurama Mom', src: `${avatarSrc}/futurama/futurama-mom.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Futurama Nibbler', src: `${avatarSrc}/futurama/futurama-nibbler.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Futurama Professor Farnsworth', src: `${avatarSrc}/futurama/futurama-professor-farnsworth.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Futurama Zapp Brannigan', src: `${avatarSrc}/futurama/futurama-zapp-brannigan.png`, rerityLeve: AvatarRerityLevels.level2},
        {title: 'Futurama Zoidberg', src: `${avatarSrc}/futurama/futurama-zoidberg.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
    'gaming': [
        {title: 'Bendy', src: `${avatarSrc}/gaming/bendy.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Day Of The Tentacle', src: `${avatarSrc}/gaming/day-of-the-tentacle.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Eggman Robotnik', src: `${avatarSrc}/gaming/eggman-robotnik.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Five Nights At Freddys', src: `${avatarSrc}/gaming/five-nights-at-freddys.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Fortnite Llama', src: `${avatarSrc}/gaming/fortnite-llama.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Fursona', src: `${avatarSrc}/gaming/fursona.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Genshin Impact Xiao', src: `${avatarSrc}/gaming/genshin-impact-xiao.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Hatsune Miku', src: `${avatarSrc}/gaming/hatsune-miku.png`, rerityLeve: AvatarRerityLevels.level8},
        {title: 'Helpy', src: `${avatarSrc}/gaming/helpy.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Jetpack Joyride', src: `${avatarSrc}/gaming/jetpack-joyride.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Luigi', src: `${avatarSrc}/gaming/luigi.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Sonic the Hedgehog', src: `${avatarSrc}/gaming/sonic-the-hedgehog.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Spyro', src: `${avatarSrc}/gaming/spyro.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Super Mario', src: `${avatarSrc}/gaming/super-mario.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Tails Prower', src: `${avatarSrc}/gaming/tails-prower.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Theodore Peterson', src: `${avatarSrc}/gaming/theodore-peterson.png`, rerityLeve: AvatarRerityLevels.level1},
        {title: 'Undyne', src: `${avatarSrc}/gaming/undyne.png`, rerityLeve: AvatarRerityLevels.level1},
    ],
    'marvel characters': [
        {title: 'Beast', src: `${avatarSrc}/marvel-characters/beast.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Black Widow', src: `${avatarSrc}/marvel-characters/black-widow.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Captain America', src: `${avatarSrc}/marvel-characters/captain-america.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Cyclops Marvel', src: `${avatarSrc}/marvel-characters/cyclops-marvel.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Deadpool', src: `${avatarSrc}/marvel-characters/deadpool.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Gambit', src: `${avatarSrc}/marvel-characters/gambit.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Groot', src: `${avatarSrc}/marvel-characters/groot.png`, rerityLeve: AvatarRerityLevels.level8},
        {title: 'Hawkeye', src: `${avatarSrc}/marvel-characters/hawkeye.png`, rerityLeve: AvatarRerityLevels.level7},
        {title: 'Hellcat', src: `${avatarSrc}/marvel-characters/hellcat.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Hulk', src: `${avatarSrc}/marvel-characters/hulk.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Human Torch', src: `${avatarSrc}/marvel-characters/human-torch.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Iron Man', src: `${avatarSrc}/marvel-characters/iron-man.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Jean Grey', src: `${avatarSrc}/marvel-characters/jean-grey.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Jessica Jones', src: `${avatarSrc}/marvel-characters/jessica-jones.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Logan X Men', src: `${avatarSrc}/marvel-characters/logan-x-men.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Luke Cage', src: `${avatarSrc}/marvel-characters/luke-cage.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Magneto', src: `${avatarSrc}/marvel-characters/magneto.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Mystique', src: `${avatarSrc}/marvel-characters/mystique.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Professor X', src: `${avatarSrc}/marvel-characters/professor-x.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Purple Man', src: `${avatarSrc}/marvel-characters/purple-man.png`, rerityLeve: AvatarRerityLevels.level7},
        {title: 'Spider-Man Head', src: `${avatarSrc}/marvel-characters/spider-man-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Storm Marvel', src: `${avatarSrc}/marvel-characters/storm-marvel.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Thanos', src: `${avatarSrc}/marvel-characters/thanos.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Thor', src: `${avatarSrc}/marvel-characters/thor.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Venom Head', src: `${avatarSrc}/marvel-characters/venom-head.png`, rerityLeve: AvatarRerityLevels.level6},
        {title: 'Wolverine', src: `${avatarSrc}/marvel-characters/wolverine.png`, rerityLeve: AvatarRerityLevels.level6},
    ],
};